### ISSUE TITLE
Can't hover on iOS

### ISSUE THREAD

**Issue by lkellar** [puffyboa/coronamap#1]
On iOS 13.3 (Latest at the time of writing), I am unable to access the information gained by hovering over the states via either of the following methods.

- **Hovering**: You can't hover on an iPhone
- **Clicking**: That just zooms in

Is there anyway you could detect taps and make that pop up the info? Or if clicks in general aren't being used, also have those pop up the info screen until something else it clicked?

**Comment by jpsank** [comment]
Fixed with [fix mobile compatibility](https://github.com/puffyboa/coronamap/commit/2e255d9c31e7e211256abe3842a75fad584bdd9e)
